### ISSUE TITLE
Set SET_TX_DESC_DISRTSFB_8822E(ptxdesc, 1); for RTS frames

### ISSUE THREAD

**Issue by svpcom** [libc0607/rtl88x2eu-20230815#2]
Hi,
I've analyzed driver source and found that `SET_TX_DESC_DISRTSFB_8822E(ptxdesc, 1);` seems should be set for injected frame if it is management frame (for example RTS).

https://github.com/libc0607/rtl88x2eu-20230815/blob/54b15d9d40dd7313b5d77e9c510d4c34d773ecf1/hal/rtl8822e/usb/rtl8822eu_xmit.c#L138

Here https://github.com/libc0607/rtl88x2eu-20230815/blob/54b15d9d40dd7313b5d77e9c510d4c34d773ecf1/hal/rtl8822e/rtl8822e_ops.c#L3572  disable RTSFB + DATAFB was set for management frames

`FB` is seems to be data rate fallback

**Comment by libc0607** [comment]
Fixed, thanks.  

Didn't notice that beamforming code😂
