### ISSUE TITLE
dkms-install broken for arm64 builds

### ISSUE THREAD

**Issue by JohnDGodwin** [libc0607/rtl88x2eu-20230815#6]
The September 23rd commits broke the build process for aarch64, specifically on the radxa zero 3.

![build](https://github.com/user-attachments/assets/ee188c20-714e-413b-b353-711b455f1f95)

**Comment by libc0607** [comment]
My Radxa finally arrived. I've tested the Sep. 23rd code, and it seems ok for my board. The only thing to notice is the ```CONFIG_PLATFORM_*``` macro in Makefile should be set correctly. 
Before run the dkms script, make sure that ```CONFIG_PLATFORM_ARM64_RPI``` is set to ```y``` and ```CONFIG_PLATFORM_I386_PC``` is ```n```. 
I'll update the readme then. 

<img width="612" alt="84bc9ce5eee8cbe54ecdcd14d3e50d1" src="https://github.com/user-attachments/assets/3465038b-cd49-46e9-8200-5f85c6095e39">

<img width="602" alt="679613586c7d6bc07d6298b313c1cf4" src="https://github.com/user-attachments/assets/a1bdee80-1db4-4707-a13f-e714c458b598">
